title: Data-Envelopes Information Page
description: All you need to know about data-envelopes for making datasets better findable, understandable and reusable.
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
sidebar:
 - homepage
